// --- CONFIGURAÇÃO DE ATIVAÇÃO DE APPS ---

const activationData = {
    // Valor de cada crédito em Reais.
    valor_credito_brl: 25.00,

    // Chave PIX (aleatória, celular, email, etc.)
    chave_pix: "altnixtecnologia@gmail.com",
    nome_beneficiario: "CRISTIAN ADAM BERAO",
    cidade_beneficiario: "FLORIANOPOLIS",

    // Lista de aplicativos e quantos créditos cada um consome.
    // O nome aqui deve ser EXATAMENTE igual ao do menu.js
    apps: {
        // Apps com fluxo especial (direto para o suporte)
        "SET IPTV": { creditos: 7, type: 'support' },

        // App com fluxo de ativação por email/senha
        "CLOUDDY": { creditos: 2, type: 'clouddy' },

        // Apps com fluxo padrão de PIX
        "IBO PLAYER PRO": { creditos: 1, type: 'pix' },
        "IBO PLAYER": { creditos: 1, type: 'pix' },
        "VU PLAYER PRO": { creditos: 1, type: 'pix' },
        "QUICK PLAYER": { creditos: 1, type: 'pix' },
        "BOB PLAYER": { creditos: 1, type: 'pix' },
        "LAZER PLAYER": { creditos: 1, type: 'pix' },
        "NINJA PLAYER": { creditos: 1, type: 'pix' },
        "IPTV PLAYERIO": { creditos: 1, type: 'pix' },
        "4K IPTV": { creditos: 1, type: 'pix' },
        "IPTV PLUS": { creditos: 1, type: 'pix' },
        "DERAM TV": { creditos: 1, type: 'pix' },
        "BAY TV": { creditos: 1, type: 'pix' },
        "VIZZION PLAY": { creditos: 1, type: 'pix' },
        "IPTV PLAYER": { creditos: 1, type: 'pix' },
        "IPTV OTT PLAYER": { creditos: 1, type: 'pix' },
        "STAR IPTV": { creditos: 1, type: 'pix' },
        "CAP PLAYER": { creditos: 1, type: 'pix' },
        "LUMINA PLAYER": { creditos: 1, type: 'pix' },
        "EASE PLAYER": { creditos: 1, type: 'pix' },
        "META PLAYER": { creditos: 1, type: 'pix' },
        "TIVI PLAYER": { creditos: 1, type: 'pix' },
        "ENZO PLAYER": { creditos: 1, type: 'pix' },
        "IPTV PRO": { creditos: 1, type: 'pix' },
        "PLAY IPTV": { creditos: 1, type: 'pix' },
        "QUICK PLAY BLACK": { creditos: 1, type: 'pix' },
        "SMARTERS MAX": { creditos: 1, type: 'pix' },
        "ASSIST PLUS": { creditos: 1, type: 'pix' },
        "CORE PLAYER": { creditos: 1, type: 'pix' },
        "ABE PLAYER": { creditos: 1, type: 'pix' },
        "RV PLAYER": { creditos: 1, type: 'pix' },
        "RIVOLUT PLAYER": { creditos: 1, type: 'pix' },
        "PLAYSIM": { creditos: 1, type: 'pix' },
        "TVIP PLAYER": { creditos: 1, type: 'pix' },
        "PRO PLAYER": { creditos: 1, type: 'pix' },
        "VIRGINIA PLAYER": { creditos: 1, type: 'pix' },
        "TERRY PLAYER": { creditos: 1, type: 'pix' },
        "UK IPTV 4K": { creditos: 1, type: 'pix' },
        "EGO IPTV": { creditos: 1, type: 'pix' },
        "TERRY IPTV": { creditos: 1, type: 'pix' },
        "BOB PRO": { creditos: 1, type: 'pix' },
        "IBO SOL": { creditos: 1, type: 'pix' },
        "VUX PLAYER": { creditos: 1, type: 'pix' },
        "MAX MEDIA PLAYER": { creditos: 1, type: 'pix' },
        "IBO STB": { creditos: 1, type: 'pix' },
        "FLIXTRA PLAYER": { creditos: 1, type: 'pix' },
        "ALL PLAYER": { creditos: 1, type: 'pix' },
        "KING 4K": { creditos: 1, type: 'pix' },
        "IBOSS IPTV": { creditos: 1, type: 'pix' },
        "FLIXNET PLAYER": { creditos: 1, type: 'pix' },
        "OTT PLAY": { creditos: 1, type: 'pix' },
        "IPTV SMARTERS": { creditos: 1, type: 'pix' },
        "UNTV PLAYER": { creditos: 1, type: 'pix' },
        "SCANDIC IPTV PLAYER": { creditos: 1, type: 'pix' },
        "SMART ONE PRO": { creditos: 1, type: 'pix' },
        "BOBPREMIUM": { creditos: 1, type: 'pix' },
        "IPTV NEXT": { creditos: 1, type: 'pix' },
        "MIRO PLAYER": { creditos: 1, type: 'pix' },
        "MAC MEDIA PLAYER": { creditos: 1, type: 'pix' },
        "KTN": { creditos: 1, type: 'pix' },
        "FAMIILY 4K": { creditos: 1, type: 'pix' },
        "M3U IPTV PLAYER": { creditos: 1, type: 'pix' },
        "POP PLAYER": { creditos: 1, type: 'pix' },
        "D HUB IPTV": { creditos: 1, type: 'pix' },
        "FENIX PLAYER": { creditos: 1, type: 'pix' },
        "TV VISION": { creditos: 1, type: 'pix' },
        "AI PLAYER": { creditos: 1, type: 'pix' },
        "HUSH PLAY": { creditos: 1, type: 'pix' },
        "A PLUS PLAYER": { creditos: 1, type: 'pix' },
        "LAXY PLAYER": { creditos: 1, type: 'pix' },
        "ION PLAYER": { creditos: 1, type: 'pix' },
        "QUEEN TV": { creditos: 1, type: 'pix' },
        "GALAXY TV": { creditos: 1, type: 'pix' },
        "NUBIA TV": { creditos: 1, type: 'pix' },
        "TEVIS TV": { creditos: 1, type: 'pix' },
        "ITELSMARTER PLAYER": { creditos: 1, type: 'pix' },
        "HOME IPTV": { creditos: 1, type: 'pix' },
        "MULTI PLAY": { creditos: 1, type: 'pix' },
        "KING 4K OTT PLAYER": { creditos: 1, type: 'pix' },
        "KIDS PLAY": { creditos: 1, type: 'pix' },
        "BLINK PLAYER": { creditos: 1, type: 'pix' },
        "FLIX TV PLAY": { creditos: 1, type: 'pix' },
        "SMART IPTV PLAY": { creditos: 1, type: 'pix' },
        "GREEN PLAYER": { creditos: 1, type: 'pix' },
        "KIWI 4K PLAYER": { creditos: 1, type: 'pix' },
        "DONTV": { creditos: 1, type: 'pix' },
        "ARAIBISK PLAYER": { creditos: 1, type: 'pix' },
        "DTV SOL": { creditos: 1, type: 'pix' },
        "DIRETV PLAY": { creditos: 1, type: 'pix' },
        "VIP": { creditos: 1, type: 'pix' },
        "SKY PLAY PLUS": { creditos: 1, type: 'pix' },
        "SPORTS TV": { creditos: 1, type: 'pix' },
        "ZEBRA PLAYER": { creditos: 1, type: 'pix' },
        "MCV PLAYER": { creditos: 1, type: 'pix' },
        "WORLD VISION IPTV": { creditos: 1, type: 'pix' },
        "CONECTADOS TV": { creditos: 1, type: 'pix' },
        "TVOYATV": { creditos: 1, type: 'pix' },
        "XTREAMUITV": { creditos: 1, type: 'pix' },
        "NUM PLAYER": { creditos: 1, type: 'pix' },
        "SMARTERS IPTV PLAYER": { creditos: 1, type: 'pix' },
        "VIVO PLAYER": { creditos: 1, type: 'pix' },
        "SUPER PLAYER": { creditos: 1, type: 'pix' },
        "FLIX PRO PLAYER": { creditos: 1, type: 'pix' },
        "IPTVSMARTERSPLAYER": { creditos: 1, type: 'pix' },
        "DUPLECAST IPTV": { creditos: 1, type: 'pix' },
        "SMART ONE": { creditos: 2, type: 'pix' },
        "MIKA PLAYER": { creditos: 1, type: 'pix' },
        "ORA PLAYER": { creditos: 1, type: 'pix' },
        "ORA IPTV PLAYER": { creditos: 1, type: 'pix' },
        "HD PLAYER": { creditos: 1, type: 'pix' },
        "9XTREAM 4K PLAYER": { creditos: 1, type: 'pix' },
        "IPTV SMARTERS LITE": { creditos: 1, type: 'pix' },
        "CR7 PLAYER": { creditos: 1, type: 'pix' },
        "FUN PLAY": { creditos: 1, type: 'pix' },
        "IBO SMARTERS": { creditos: 1, type: 'pix' },
        "IBO XPLAYER": { creditos: 1, type: 'pix' },
        "IPTV SMARTER 4K PLAYER": { creditos: 1, type: 'pix' },
        "SMART LIVE TV": { creditos: 1, type: 'pix' },
        "IPTV SMART 4K PLAYER": { creditos: 1, type: 'pix' },
        "SIMPLE PRO": { creditos: 1, type: 'pix' },
        "ULTRA PLAYER": { creditos: 1, type: 'pix' }
    }
};

module.exports = activationData;