const menu = {
    tv: {
        titulo: "📺 *Planos MagiaTV (Filmes e Séries em Alta)*",
        opcoes: [
            "*🥈 PLANO PRATA (Custo-Benefício)*",
            "Mensal - R$ 35,00",
            "Trimestral - R$ 85,00",
            "Semestral - R$ 140,00",
            "Anual - R$ 190,00 (App de brinde para SmartTV)",
            "",
            "*💎 PLANO DIAMANTE (Premium 4K)*",
            "Mensal - R$ 45,00",
            "Trimestral - R$ 115,00",
            "Semestral - R$ 180,00",
            "Anual - R$ 280,00"
        ]
    },
    apps: {
        titulo: "📱 *Ativação de Aplicativos*",
        opcoes: [
            "4K IPTV",
            "9XTREAM 4K PLAYER",
            "A PLUS PLAYER",
            "ABE PLAYER",
            "AI PLAYER",
            "ALL PLAYER",
            "ARAIBISK PLAYER",
            "ASSIST PLUS",
            "BAY TV",
            "BLINK PLAYER",
            "BOB PLAYER",
            "BOB PRO",
            "BOBPREMIUM",
            "CAP PLAYER",
            "CLOUDDY",
            "CONECTADOS TV",
            "CORE PLAYER",
            "CR7 PLAYER",
            "D HUB IPTV",
            "DERAM TV",
            "DIRETV PLAY",
            "DONTV",
            "DTV SOL",
            "DUPLECAST IPTV",
            "EASE PLAYER",
            "EGO IPTV",
            "ENZO PLAYER",
            "FAMIILY 4K",
            "FENIX PLAYER",
            "FLIX PRO PLAYER",
            "FLIX TV PLAY",
            "FLIXNET PLAYER",
            "FLIXTRA PLAYER",
            "FUN PLAY",
            "GALAXY TV",
            "GREEN PLAYER",
            "HD PLAYER",
            "HOME IPTV",
            "HUSH PLAY",
            "IBO PLAYER",
            "IBO PLAYER PRO",
            "IBO SMARTERS",
            "IBO SOL",
            "IBO STB",
            "IBO XPLAYER",
            "IBOSS IPTV",
            "ION PLAYER",
            "IPTV NEXT",
            "IPTV OTT PLAYER",
            "IPTV PLAYER",
            "IPTV PLAYERIO",
            "IPTV PRO",
            "IPTV PLUS",
            "IPTV SMARTER 4K PLAYER",
            "IPTV SMARTERS",
            "IPTV SMARTERS LITE",
            "IPTVSMARTERSPLAYER",
            "IPTV SMART 4K PLAYER",
            "ITELSMARTER PLAYER",
            "KIDS PLAY",
            "KING 4K",
            "KING 4K OTT PLAYER",
            "KIWI 4K PLAYER",
            "KTN",
            "LAZER PLAYER",
            "LAXY PLAYER",
            "LUMINA PLAYER",
            "M3U IPTV PLAYER",
            "MAC MEDIA PLAYER",
            "MAX MEDIA PLAYER",
            "MCV PLAYER",
            "META PLAYER",
            "MIKA PLAYER",
            "MIRO PLAYER",
            "MULTI PLAY",
            "NINJA PLAYER",
            "NUBIA TV",
            "NUM PLAYER",
            "ORA IPTV PLAYER",
            "ORA PLAYER",
            "OTT PLAY",
            "PLAY IPTV",
            "PLAYSIM",
            "POP PLAYER",
            "PRO PLAYER",
            "QUEEN TV",
            "QUICK PLAYER",
            "QUICK PLAY BLACK",
            "RIVOLUT PLAYER",
            "RV PLAYER",
            "SCANDIC IPTV PLAYER",
            "SET IPTV",
            "SIMPLE PRO",
            "SKY PLAY PLUS",
            "SMART IPTV PLAY",
            "SMART LIVE TV",
            "SMART ONE",
            "SMART ONE PRO",
            "SMARTERS IPTV PLAYER",
            "SMARTERS MAX",
            "SPORTS TV",
            "STAR IPTV",
            "SUPER PLAYER",
            "TERRY IPTV",
            "TERRY PLAYER",
            "TEVIS TV",
            "TIVI PLAYER",
            "TV VISION",
            "TVIP PLAYER",
            "TVOYATV",
            "UK IPTV 4K",
            "ULTRA PLAYER",
            "UNTV PLAYER",
            "VIP",
            "VIRGINIA PLAYER",
            "VIVO PLAYER",
            "VU PLAYER PRO",
            "VUX PLAYER",
            "VIZZION PLAY",
            "WORLD VISION IPTV",
            "XTREAMUITV",
            "ZEBRA PLAYER"
        ]
    },
    pix: "altnixtecnologia@gmail.com",
    suporte: "https://wa.me/5511996554229"
};

module.exports = menu;
